"""create database

Revision ID: aa90818a629e
Revises: 
Create Date: 2023-09-12 23:43:52.142848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'aa90818a629e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('username', sa.String(), nullable=True),
                    sa.Column('first_name', sa.String(), nullable=True),
                    sa.Column('last_name', sa.String(), nullable=True),
                    sa.Column('hashed_password', sa.String(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('role', sa.String(), nullable=True),
                    sa.Column('user_phone_number', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_user_phone_number'), 'users', ['user_phone_number'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('message',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('sender_id', sa.Integer(), nullable=True),
                    sa.Column('receiver_no', sa.String(), nullable=True),
                    sa.Column('message_text', sa.Text(), nullable=True),
                    sa.Column('sent_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    op.create_table('whatsapp_credentials',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('api_token', sa.String(), nullable=True),
                    sa.Column('phone_number', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['phone_number'], ['users.user_phone_number'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_whatsapp_credentials_api_token'), 'whatsapp_credentials', ['api_token'], unique=True)
    op.create_index(op.f('ix_whatsapp_credentials_id'), 'whatsapp_credentials', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_credentials_phone_number'), 'whatsapp_credentials', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_credentials_phone_number'), table_name='whatsapp_credentials')
    op.drop_index(op.f('ix_whatsapp_credentials_id'), table_name='whatsapp_credentials')
    op.drop_index(op.f('ix_whatsapp_credentials_api_token'), table_name='whatsapp_credentials')
    op.drop_table('whatsapp_credentials')
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
